baseurl: "https://unixwinbsd.github.io" 
title: WARNET DAPURNET
languageCode: "id-ID"
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Anonymous
          url: anonymous/
          weight: 5 
        - name: DataBase
          url: database/
          weight: 5
        - name: DNSServer
          url: dnsserver/
          weight: 3
        - name: WebHTTPS
          url: webhttps/
          weight: 4 
        - name: Blog
          url: https://unixwinbsd.site
          weight: 6

params:
    description: "WEB HTTP HTTPS"
    author: IWAN SETIAWAN
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["anonymous","dnsserver","database","webhttps"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: WARNET DAPURNET
          subtitle: "WARNET DAPURNET adalah platform pembelajaran daring yang menyediakan tutorial dan video daring tentang Blogger. Tak hanya itu, WARNET DAPURNET juga menyajikan berbagai macam topik, termasuk pengembangan perangkat lunak, pemrograman, desain web, dan banyak lagi. Blog ini menyajikan berbagai tutorial dan video pembelajaran untuk pemula dan profesional berpengalaman."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: DataBase
              url: database/
            - name: WebHTTPS
              url: webhttps/
            - name: Anonymous
              url: anonymous/
            - name: DNSServer
              url: dnsserver/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: GitFlic
          url: https://gitflic.ru/user/unixbsdshell
        - name: Email
          url: datainchi@gmail.com
        - name: Zoom
          url: https://www.zoom.us/my/igelfeld
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/pmichaillat
        - name: Substack
          url: https://pmichaillat.substack.com
        - name: YouTube
          url: https://www.youtube.com/@pmichaillat
        - name: Twitter
          url: https://x.com/pmichaillat
        - name: Bluesky
          url: https://bsky.app/profile/pmichaillat.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "WARNET DAPURNET"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
